# permissions for end users to view testings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testing-viewer-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - testings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - testings/status
  verbs:
  - get
