# permissions for end users to edit testings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testing-editor-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - testings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - testings/status
  verbs:
  - get
